---
title: "R Weather Project For Beginners"
author: "Reginald Erzoah"
date: "2024-11-30"
output: html_document
---

Load the required packages
```{r}
library(readr)
library(dplyr)
library(ggplot2)
```


Import the data
```{r}
weather_data <- read_csv("weatherHistory.csv")
```

View the data summary 
```{r}
summary(weather_data)
```

Calculate the average temperature per year
```{r}
Avg_Yearly_Temp <- weather_data %>%
  mutate(
    Date = as.Date(`Formatted Date`),
    Year = format(Date,"%Y")
  )%>%
  group_by(Year)%>%
  summarise(Avg_Temp = mean(`Temperature (C)`, na.rm = TRUE))
```

View the results of the Yearly Average Temperature Calculation
```{r}
print(Avg_Yearly_Temp)
```

Plot the average temperature per year as a bar chart
```{r}
ggplot(Avg_Yearly_Temp,aes(x= Year, y=Avg_Temp))+
  geom_bar(stat = "identity",fill="blue")+
  labs(
    title = "Average Yearly Temperature",
    x = "Year",
    y = "Average Temperature (C)"
  )
```

